# Default smoke test generated by COMET
import pathlib


def test_module_placeholder():
    # Keep a simple sanity check so CI passes by default
    project_root = pathlib.Path(__file__).resolve().parents[1]
    assert project_root.exists()